import pprint

from sondesh.ddl_parser import parse_the_ddl

def test_oracle_ddl():

    ddl = '''
        CREATE TABLE employee (
            employee_id number(100),
            first_name VARCHAR2(128) NOT NULL,
            last_name VARCHAR2(128) NOT NULL,
            salary NUMBER(6) ENCRYPT USING 'SHA256',
            emp_photo Blob,
            dept_id NUMBER(10),
            car_vin_no NUMBER(*,10),            
            include_exclude_ind CHAR(1) DEFAULT 'Y',
            TEXT2_ NVARCHAR2(2000),
            CONSTRAINT check_employee_name CHECK (first_name = upper(first_name)),
            CONSTRAINT dept_fk FOREIGN KEY(dept_id) REFERENCES department(dept_id),
            CONSTRAINT employees_pk PRIMARY KEY (employee_id)
        )  
        PARTITION BY REFERENCE(dept_fk)
        Storage ( Initial 5m Next 5m Maxextents Unlimited )
        ;
    '''

    result = parse_the_ddl(ddl).run(group_by_type=True)
    pprint.pprint(result)

    expected = '''
                    {'ddl_properties': [],
                 'domains': [],
                 'schemas': [],
                 'sequences': [],
                 'tables': [{'alter': {},
                             'checks': [{'constraint_name': 'check_employee_name',
                                         'statement': 'first_name = upper(first_name)'}],
                             'columns': [{'check': None,
                                          'default': None,
                                          'name': 'employee_id',
                                          'nullable': False,
                                          'references': None,
                                          'size': 100,
                                          'type': 'number',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'name': 'first_name',
                                          'nullable': False,
                                          'references': None,
                                          'size': 128,
                                          'type': 'VARCHAR2',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'name': 'last_name',
                                          'nullable': False,
                                          'references': None,
                                          'size': 128,
                                          'type': 'VARCHAR2',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'encrypt': {'encryption_algorithm': "'SHA256'",
                                                      'integrity_algorithm': 'SHA-1',
                                                      'salt': True},
                                          'name': 'salary',
                                          'nullable': True,
                                          'references': None,
                                          'size': 6,
                                          'type': 'NUMBER',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'name': 'emp_photo',
                                          'nullable': True,
                                          'references': None,
                                          'size': None,
                                          'type': 'Blob',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'name': 'dept_id',
                                          'nullable': True,
                                          'references': None,
                                          'size': 10,
                                          'type': 'NUMBER',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'name': 'car_vin_no',
                                          'nullable': True,
                                          'references': None,
                                          'size': ('*', 10),
                                          'type': 'NUMBER',
                                          'unique': False},
                                         {'check': None,
                                          'default': "'Y'",
                                          'name': 'include_exclude_ind',
                                          'nullable': True,
                                          'references': None,
                                          'size': 1,
                                          'type': 'CHAR',
                                          'unique': False},
                                         {'check': None,
                                          'default': None,
                                          'name': 'TEXT2_',
                                          'nullable': True,
                                          'references': None,
                                          'size': 2000,
                                          'type': 'NVARCHAR2',
                                          'unique': False}],
                             'constraints': {'checks': [{'constraint_name': 'check_employee_name',
                                                         'statement': 'first_name = '
                                                                      'upper(first_name)'}],
                                             'primary_keys': [{'columns': ['employee_id'],
                                                               'constraint_name': 'employees_pk'}],
                                             'references': [{'columns': ['dept_id'],
                                                             'constraint_name': 'dept_fk',
                                                             'deferrable_initially': None,
                                                             'on_delete': None,
                                                             'on_update': None,
                                                             'schema': None,
                                                             'table': 'department'}]},
                             'index': [],
                             'partition_by': {'columns': ['dept_fk'], 'type': 'REFERENCE'},
                             'partitioned_by': [],
                             'primary_key': ['employee_id'],
                             'schema': None,
                             'storage': {'initial': '5m',
                                         'maxextents': 'Unlimited',
                                         'next': '5m'},
                             'table_name': 'employee',
                             'tablespace': None}],
                 'types': []}
    '''
    #assert expected == result
    pprint.pprint(result['tables'][0]['checks'])

test_oracle_ddl()